### ISSUE TITLE
aacraid-status paring error

### ISSUE THREAD

**Issue by iotaka** [eLvErDe/hwraid#112]
Hello Adam @eLvErDe 

we have a machine with a failing disk and running aacraid-status it fail on the parsing of arcconf output

```
aacraid-status            
-- Controller informations --
-- ID | Model | Status
c0 | Adaptec ASR8805 | Optimal

-- Arrays informations --
-- ID | Type | Size | Status | Task | Progress
Traceback (most recent call last):
  File "/usr/sbin/aacraid-status", line 268, in <module>
    arrayinfo = returnArrayInfo(output, ctrl_id=controllerid)
  File "/usr/sbin/aacraid-status", line 101, in returnArrayInfo
    device_state = re.search('\s+\((.*)\)\s+', line).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

In attachment the output of arcconf and a small patch that fixes the problem.

**Comment by iotaka** [comment]
Here the files


[arcconf.txt](https://github.com/eLvErDe/hwraid/files/3916975/arcconf.txt)
[arcconf-patch.txt](https://github.com/eLvErDe/hwraid/files/3916981/arcconf-patch.txt)

**Comment by iotaka** [comment]
Hello Adam @eLvErDe today we had a rebuild on a server and we discover another small issue.

from **arcconf GETCONFIG 1 AL**
`   Status of Logical Device                 : Degraded, Rebuilding ( Rebuild : 68 % )`

from **aacraid-status**
```
   -- Arrays informations --
-- ID | Type | Size | Status | Task | Progress
c0u0 | RAID10 | 5713G | Degraded, Rebuilding ( Rebuild
```
we did another small fix and the output become:
`c0u0 | RAID10 | 5713G | Degraded, Rebuilding ( Rebuild  87 % ) | Rebuild | 87%`

There was also an error on
from **arcconf GETSTATUS 1** 
```
Controllers found: 1 
Logical Device Task: 
   Logical Device                 : 0 
   Task ID                        : 100 
   Current operation              : Rebuild 
   Status                         : In Progress 
   Priority                       : High 
   Percentage complete            : 85
```
Logical **D**evice didn't match so we add an IGNORECASE

[rebuild.patch.txt](https://github.com/eLvErDe/hwraid/files/3945197/rebuild.patch.txt)

Thank you, cheers :)
