### ISSUE TITLE
megaclisas-status error

### ISSUE THREAD

**Issue by secretxhun** [eLvErDe/hwraid#36]
On some systems (ubuntu 12.04, debian wheezy) after installed the new libc packages, the megaclisas-status not working:

13:40 root@xxx:/usr/sbin # ./megaclisas-status
-- Controller information --
-- ID | H/W Model         | RAM    | Temp | BBU    | Firmware
c0    | LSI 2208 MegaRAID | 1024MB | 70C  | Good   | FW: 23.33.0-0025

-- Array information --
hangup, after i ctrl+x this message is going on:

^CTraceback (most recent call last):
  File "./megaclisas-status", line 580, in <module>
    if re.match(r'^Virtual Drive:',line.strip()):
  File "/usr/lib/python2.7/re.py", line 134, in match
    def match(pattern, string, flags=0):
KeyboardInterrupt

---------

With debug i see this:

# DEBUG : Got Cached value: /usr/sbin/megacli -LDInfo -l0 -a0 -NoLog
# DEBUG : Got Cached value: /usr/sbin/megacli -LDInfo -l0 -a0 -NoLog
# DEBUG : Got Cached value: /usr/sbin/megacli -LDInfo -l0 -a0 -NoLog
# DEBUG : Got Cached value: /usr/sbin/megacli -LDInfo -l0 -a0 -NoLog

forever :), after ctrl+c:

^CTraceback (most recent call last):
  File "./megaclisas-status", line 580, in <module>
    if re.match(r'^Virtual Drive:',line.strip()):
KeyboardInterrupt

--
Please help me :) Thanks

**Comment by ElCoyote27** [comment]
Hi,
Would it be possible to send us the output of:
/usr/sbin/megacli -LDInfo -l0 -a0 -NoLog
Thanks,
Vincent

**Comment by secretxhun** [comment]
of course:

14:08 root@xxx:~ # /usr/sbin/megacli -LDInfo -l0 -a0 -NoLog


Adapter 0 -- Virtual Drive Information:
CacheCade Virtual Drive: 0 (Target Id: 0)
Virtual Drive Type    : CacheCade
Name          :
RAID Level        : Primary-1, Secondary-0
State             : Optimal
Size          : 222.585 GB
Target Id of the Associated LDs : 4,5,6,8,9,7
Default Cache Policy  : WriteBack, ReadAhead, Cached, Write Cache OK if Bad BBU
Current Cache Policy  : WriteBack, ReadAhead, Cached, Write Cache OK if Bad BBU



Exit Code: 0x00

Thanks, Andras

**Comment by ElCoyote27** [comment]
Ok, you're running into this because you have CacheCade.
I don't have access to a cache-cade enabled machine so I'll have to find 
one. In the mean time, I'll try to code something 'blindly' and send you 
an update to test later this week...
Regards,
Vincent

**Comment by secretxhun** [comment]
Thanks!

**Comment by ElCoyote27** [comment]
Do you have any idea if this was working before? If so, can you please let us know what version is known as good?
Thanks,
Vincent

**Comment by secretxhun** [comment]
i see the wrong machines, and i see ii  megaclisas-status                0.12, that not working after i install the libc6 updates.
I see another machines that working fine: ii  megaclisas-status                0.9+nmu3, but i not installed the libc6 updates after this issue on this machine :)

**Comment by secretxhun** [comment]
Okay, i see, the new megaclisas-status 0.12 installed with libc6, so i believe, not the libc6 the problem, only the megaclisas-status 0.12 version is wrong.

**Comment by ElCoyote27** [comment]
Hi,
Could you show me what the ouput looks like with 'megaclisas-status 0.9+nmu3'?
Does it work with CacheCade?
Thanks,

**Comment by secretxhun** [comment]
yes, its working:

15:36 root@xxx:~ # megaclisas-status
-- Controller information --
-- ID | Model | Firmware
c0 | LSI 2208 MegaRAID | 23.33.0-0025

-- Array information --
-- ID | Type | Size | Status | InProgress | CacheCade Info
c0u0 | RAID1 | 223G | Optimal | None | Associated : c0u4, c0u5, c0u6, c0u8, c0u9, c0u7
c0u1 | RAID1 | 223G | Optimal | None | Associated : c0u4, c0u5, c0u6, c0u8, c0u9, c0u7
c0u2 | RAID0 | 223G | Optimal | None | None
c0u3 | RAID0 | 223G | Optimal | None | None
c0u4 | RAID0 | 2727G | Optimal | None | Type : Read and Write
c0u5 | RAID0 | 2727G | Optimal | None | Type : Read and Write
c0u6 | RAID0 | 2727G | Optimal | None | Type : Read and Write
c0u7 | RAID0 | 2727G | Optimal | None | Type : Read and Write
c0u8 | RAID0 | 2727G | Optimal | None | Type : Read and Write
c0u9 | RAID0 | 2727G | Optimal | None | Type : Read and Write

-- Disk information --
-- ID | Model | Status
c0u0p0 | S1G0NYAF200036 MZ7WD240HCFV-00003 DXM9103Q | Online, Spun Up
c0u0p1 | S1G0NYAF200163 MZ7WD240HCFV-00003 DXM9103Q | Online, Spun Up
c0u1p0 | S1G0NYAF200164 MZ7WD240HCFV-00003 DXM9103Q | Online, Spun Up
c0u1p1 | S1G0NYAG401119 SAMSUNG MZ7WD240HCFV-00003 DXM9203Q | Online, Spun Up
c0u2p0 | S1G0NEAFC02928 SAMSUNG MZ7WD240HCFV-00003 DXM9203Q | Online, Spun Up
c0u3p0 | S1G0NYAF200031 MZ7WD240HCFV-00003 DXM9103Q | Online, Spun Up
c0u4p0 | Z2P33XBASTOSHIBA DT01ACA300 MX6OABB0 | Online, Spun Up
c0u5p0 | Z2O58EKASTOSHIBA DT01ACA300 MX6OABB0 | Online, Spun Up
c0u6p0 | Z2O588WASTOSHIBA DT01ACA300 MX6OABB0 | Online, Spun Up
c0u7p0 | Z1Y164BYST3000NM0033-9ZM178 SN03 | Online, Spun Up
c0u8p0 | Z2P33VXASTOSHIBA DT01ACA300 MX6OABB0 | Online, Spun Up
c0u9p0 | Z2P33WKASTOSHIBA DT01ACA300 MX6OABB0 | Online, Spun Up

**Comment by ElCoyote27** [comment]
Ok, so it's clearly a regression. Would you be able to provide me with an URL of the package that includes the version of megaclisas-status that works for you? Or could you e-mail me a copy?
Thanks,
Vincent

**Comment by secretxhun** [comment]
okay, this is:

http://pastebin.com/hNNkDv5F

**Comment by ElCoyote27** [comment]
Hi,
Thanks to your outputs and to the code you posted, I was able to write some code that -should- deal with CacheCade LD's.. Could you please give it a try? The code is at:
https://raw.githubusercontent.com/ElCoyote27/hwraid/master/wrapper-scripts/megaclisas-status
Thank you,
Vincent

**Comment by secretxhun** [comment]
Sorry, i'm here:
Not working the new code, this is the error message:


Traceback (most recent call last):
  File "./megatest", line 606, in <module>
    arrayinfo = returnArrayInfo(output, controllerid, ldid, arrayindex)
  File "./megatest", line 335, in returnArrayInfo
    associated.append('c%du%d' % (controller_id, int(array)))
NameError: global name 'controller_id' is not defined


Thanks, Andras

**Comment by ElCoyote27** [comment]
Ok, let me check that.

**Comment by ElCoyote27** [comment]
That was with this code: https://raw.githubusercontent.com/ElCoyote27/hwraid/master/wrapper-scripts/megaclisas-status,
can you confirm?

**Comment by secretxhun** [comment]
yes, same:

14:17 root@xxx:~ # ./megatest2 --nagios
Traceback (most recent call last):
  File "./megatest2", line 606, in <module>
    arrayinfo = returnArrayInfo(output, controllerid, ldid, arrayindex)
  File "./megatest2", line 335, in returnArrayInfo
    associated.append('c%du%d' % (controller_id, int(array)))
NameError: global name 'controller_id' is not defined

**Comment by ElCoyote27** [comment]
There was a minor typo, could you please re-download and test again?
Thank you,
Vincent

**Comment by ElCoyote27** [comment]
https://raw.githubusercontent.com/ElCoyote27/hwraid/master/wrapper-scripts/megaclisas-status

**Comment by secretxhun** [comment]
14:25 root@ceph03:~ # ./megatest2 --nagios
Traceback (most recent call last):
  File "./megatest2", line 702, in <module>
    arraydisk = returnDiskInfo(output,controllerid)
  File "./megatest2", line 446, in returnDiskInfo
    if (( NestedLDTable[controllerid][int(arrayindex)] == True) and (spanid != False)):
IndexError: list index out of range

**Comment by ElCoyote27** [comment]
Ok, it's a different error. I'll be checking this later today.

**Comment by secretxhun** [comment]
okay, thanks :)

**Comment by ElCoyote27** [comment]
Please try again (download and repeat):

commit 34abdc913242e8c23822c9379d2f3af008554f57
Author: Vincent S. Cojot <vincent@cojot.name>
Date:   Wed Mar 9 08:32:07 2016 -0500

    [megaclisas-status] Minor Fix for CacheCade

**Comment by secretxhun** [comment]
I dowloaded this again:
 14:38 root@xxx:~ # ./megatest3 --nagios
Traceback (most recent call last):
  File "./megatest2", line 598, in <module>
    NestedLDTable[controllerid][int(arrayindex)] = False
IndexError: list assignment index out of range

**Comment by ElCoyote27** [comment]
Can you try that again? I think I fixed the issue with the uninitialized array NestedLDTable.

**Comment by secretxhun** [comment]
Cool, working :)
This is updated to http://hwraid.le-vert.net packages also?

Thanks, Andras

**Comment by secretxhun** [comment]
14:53 root@xxx:~ # ./megatest4 --nagios
RAID OK - Arrays: OK:8 Bad:0 - Disks: OK:12 Bad:0

**Comment by ElCoyote27** [comment]
I have a pull request for @eLvErDe  but I don't think he merged it yet.
Thanks for testing.
Could you test without '--nagios' and let me know if the output is OK with you?
Thanks,
Vincent

**Comment by secretxhun** [comment]
I tested, working perfectly.
Thanks for the help :)

**Comment by ElCoyote27** [comment]
What does the output look like (without --nagios), would you mind sharing?
Thanks

**Comment by secretxhun** [comment]
http://pastebin.com/PYT47jRq

**Comment by ElCoyote27** [comment]
Thanks.
I still think we might have a bug: there are no c0u8 and c0u9 in the output..
Let me look at that again..

**Comment by ElCoyote27** [comment]
Could you please try the full output with the latest version (again)?
Many thanks for testing..
Vincent

**Comment by ElCoyote27** [comment]
Fixed in latest set of commits at: https://github.com/ElCoyote27/hwraid/commit/d2bf380ca5e27b8e8807a6486c87caf3fc53db6a
