### ISSUE TITLE
Arrcconf segfault on debian jessi 64bit

### ISSUE THREAD

**Issue by msilvoso** [eLvErDe/hwraid#51]
Hello,

Since the latest update I get segmentation faults. What do you need from me to debug?

Cheers,

Manu

**Comment by eLvErDe** [comment]
Hello,

Can you send me output of "apt-cache policy arcconf" ?

**Comment by msilvoso** [comment]
This happens since the latest update
arcconf:
  Installed: 1:2.02.22404-1
  Candidate: 1:2.02.22404-1
  Version table:
 *** 1:2.02.22404-1 0
        500 http://hwraid.le-vert.net/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
     1:1.08.21375-1 0
        500 http://hwraid.le-vert.net/debian/ jessie/main amd64 Packages
     1:1.07.21229-1 0
        500 http://hwraid.le-vert.net/debian/ jessie/main amd64 Packages
     1:1.05.20942-1 0
        500 http://hwraid.le-vert.net/debian/ jessie/main amd64 Packages
     7.31.18856-1 0
        500 http://hwraid.le-vert.net/debian/ jessie/main amd64 Packages

The only version which works is the 7.31.18856-1, all the other produce a segfault on my server

Have a nice day,

Manu

**Comment by msilvoso** [comment]
I have put the package on hold

**Comment by eLvErDe** [comment]
Hello,

Well, that's why I provided all versions but there's clearly something wrong on your server.
Can you send me output of ldd /usr/sbin/arcconf when installing a newer version ?

Regards, Adam.

**Comment by s-hemer** [comment]
Same here but on a really old Dell PowerEdge 2650 running Debian 8 i386. All the 1:1.0xxx versions segfault, 7.31.xxx works.
Server crashed two times after the upgrade to 1:1.08. Reverted and put on hold, now monitoring and hope it runs again stable.

**Comment by msilvoso** [comment]
arcconf (1:2.02.22404-1)
:~# ldd /usr/sbin/arcconf
        linux-vdso.so.1 (0x00007ffd09d49000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f59832f1000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f59830d4000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5982dc9000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5982ac8000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f59828b2000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5982507000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f59834f5000)

arcconf (1:1.08.21375-1) ...
:~# ldd /usr/sbin/arcconf
        linux-vdso.so.1 (0x00007ffd947ab000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f697a1c7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6979faa000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6979c9f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f697999e000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6979788000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f69793dd000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f697a3cb000)

arcconf (1:1.07.21229-1) ...
:~# ldd /usr/sbin/arcconf
        linux-vdso.so.1 (0x00007ffd4ed39000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f44d5064000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f44d4e47000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f44d4b3c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f44d483b000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f44d4625000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f44d427a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f44d5268000)

arcconf (1:1.05.20942-1) ...
:~# ldd /usr/sbin/arcconf
        linux-vdso.so.1 (0x00007ffe4bbd1000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f5be5378000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f5be515b000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f5be4e50000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f5be4b4f000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f5be4939000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f5be458e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f5be557c000)

arcconf (7.31.18856-1) ... (the one that works)
:~# ldd /usr/sbin/arcconf
        linux-vdso.so.1 (0x00007ffc2e51d000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f701c926000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f701c709000)
        libstdc++.so.5 => /usr/lib/x86_64-linux-gnu/libstdc++.so.5 (0x00007f701c42d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f701c12c000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f701bf16000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f701bb6b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f701cb2a000)

**Comment by devup** [comment]
I have the same problem

> Nov 10 08:44:44 debian kernel: [76855.575052] arcconf[18598]: segfault at 10 ip 00000000007d18e9 sp 00007ffcbd0d8470 error 4 in arcconf[400000+e69000]

root@debian:/var/log# apt-cache policy arcconf
arcconf:
  Installed: 1:2.02.22404-1
  Candidate: 1:2.02.22404-1
  Version table:
 *** 1:2.02.22404-1 0
        500 http://hwraid.le-vert.net/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status
     1:1.08.21375-1 0
        500 http://hwraid.le-vert.net/debian/ jessie/main amd64 Packages
     1:1.07.21229-1 0
        500 http://hwraid.le-vert.net/debian/ jessie/main amd64 Packages
     1:1.05.20942-1 0
        500 http://hwraid.le-vert.net/debian/ jessie/main amd64 Packages
     7.31.18856-1 0
        500 http://hwraid.le-vert.net/debian/ jessie/main amd64 Packages
root@debian:/var/log# ldd /usr/sbin/arcconf
        linux-vdso.so.1 (0x00007ffc185cd000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f88833b4000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8883197000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8882e8c000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8882b8b000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8882975000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f88825ca000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f88835b8000)

**Comment by mika** [comment]
Same here with a fully up2date Debian/jessie system, kernel 3.16.0-4-amd64 (3.16.36-1+deb8u2) on IBM System x3650 hardware, reproducible on several of our servers.

The 1.05, 1.07, 1.08 + 2.02 package versions are affected (all segfaulting), only version 7.31 works as expected.

Some further information from syslog + gdb (I'm aware that this doesn't really provide much additional information):

````
Nov 10 23:41:08 [snip] kernel: [15040.467962] arcconf_1.08[29247]: segfault at 10 ip 0000000000558979 sp 00007ffe424a6040 error 4 in arcconf_1.08[400000+246000]
[...]
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
[....]
[New LWP 28482]
[New LWP 28483]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./arcconf_1.08 getconfig 1 AL'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000558979 in ?? ()
(gdb) bt
#0  0x0000000000558979 in ?? ()
#1  0x000000000050de1b in ?? ()
#2  0x000000000053909d in ?? ()
#3  0x0000000000494f0b in ?? ()
#4  0x000000000042aed4 in ?? ()
#5  0x00007fe7a608fb45 in __libc_start_main (main=0x42abc0, argc=4, argv=0x7fff3a11aec8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff3a11aeb8) at libc-start.c:287
#6  0x00000000004096c9 in ?? ()
#7  0x00007fff3a11aeb8 in ?? ()
#8  0x000000000000001c in ?? ()
#9  0x0000000000000004 in ?? ()
#10 0x00007fff3a11c909 in ?? ()
#11 0x00007fff3a11c918 in ?? ()
#12 0x00007fff3a11c922 in ?? ()
#13 0x00007fff3a11c924 in ?? ()
#14 0x0000000000000000 in ?? ()
(gdb) quit
````

**Comment by tpdownes** [comment]
I am seeing the same problem. Suspect use of libstdc++6 vs libstdc++5 is part of the story.

**Comment by fluxcorenz** [comment]
Also seeing segfault on a debian wheezy sun fire x4170 server w/arcconf 1:2.02.22404-1. Reverting to version 7.31.18856-1 reinstates functionality.

~#  ldd /usr/sbin/arcconf
	linux-vdso.so.1 =>  (0x00007fff1a9e2000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9f513ac000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9f51190000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9f50e89000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9f50c07000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9f509f1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9f50664000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9f515b0000)

**Comment by geosone** [comment]
could you try to use my package where i hope  i included the right libstdc++.so http://ftp.disconnected-by-peer.at/go-hwraid/pool/main/a/arcconf/

**Comment by geosone** [comment]
tomorrow my repo will contain a new version of my version of arcconf package

**Comment by tpdownes** [comment]
@geosone I still see a segfault with =2.05.3-1~20171111184405.17+jessie=
```
root@pcdev1:~# arcconf GETCONFIG 1
Controllers found: 1
Segmentation fault
```
It seems to be looking for a [filename that does not exist in any debian package](https://packages.debian.org/search?suite=stretch&arch=any&mode=path&searchon=contents&keywords=libstdcv4.so.6):
```
root@pcdev1:~# ldd /usr/lib/arcconf/arcconf-2.05
	linux-vdso.so.1 (0x00007ffd16fce000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7f6299e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7f62781000)
	libstdcv4.so.6 => not found
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7f62480000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7f6226a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7f61ebf000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7f62ba2000)
```

**Comment by geosone** [comment]
ist provided /usr/lib/arcconf/libstdcv4.so.6 wiht the package 
i really hepd this packag would work. the bash script that loads the bin has an modifeid LD_PATH

**Comment by tpdownes** [comment]
I think that linking is probably better handled during compilation. Either way, it's not important enough to me to pursue much further. The "old" package works just fine for me.

**Comment by stefangweichinger** [comment]
I know this is old, but still "Open": I hit segfaults with arcconf on Gentoo Linux and look for a working static binary.
I'd be OK with some older release, the server to be maintained runs legacy hardware.
