### ISSUE TITLE
megaclisas-status (jbod + PERC H730P Mini) "IndexError: list assignment index out of range"

### ISSUE THREAD

**Issue by camypaj** [eLvErDe/hwraid#54]
Hi all,

thanks for maintaining this repository and scripts, it's a life-saver :)
That being said, I seem to have an issue with my JBOD setup, (which might be a regression, I'm not sure)
Controller: PERC H730P Mini
os: debian jessie, 64bit
version(s) installed: megacli 8.07.14-1, megaclisas-status 0.15, daemon 0.6.4, python 2.7.9
Edit: arrays are consecutive (0-24)

```
# megaclisas-status
-- Controller information --
-- ID | H/W Model       | RAM    | Temp | BBU    | Firmware     
c0    | PERC H730P Mini | 2048MB | 48C  | Good   | FW: 25.4.1.0004 

-- Array information --
Traceback (most recent call last):
  File "/usr/sbin/megaclisas-status", line 637, in <module>
    arrayinfo = returnArrayInfo(output, controllerid, ldid, arrayindex)
  File "/usr/sbin/megaclisas-status", line 369, in returnArrayInfo
    NestedLDTable[int(controllerid)][int(arrayindex)] = False
IndexError: list assignment index out of range
```
I've also tried a few versions from @ElCoyote27 (including latest), and it also fails.

Interestingly enough, --debug says it fails with logical drive 16 (out of 24)?!
```
# megaclisas-status --debug
...
-- Array information --
# DEBUG : Not a Cached value: /usr/sbin/megacli -LDInfo -lall -a0 -NoLog
# DEBUG : Not a Cached value: /usr/sbin/megacli -LDInfo -l0 -a0 -NoLog
...
# DEBUG : Not a Cached value: /usr/sbin/megacli -LDInfo -l24 -a0 -NoLog
# DEBUG : Got Cached value: /usr/sbin/megacli -LDInfo -l0 -a0 -NoLog
# DEBUG : RAID Level: 1 Span Depth: 1 Disk Per Span: 0 Raid Type: RAID-1
............
# DEBUG : Got Cached value: /usr/sbin/megacli -LDInfo -l16 -a0 -NoLog
Traceback (most recent call last):
  File "/usr/sbin/megaclisas-status", line 637, in <module>
    arrayinfo = returnArrayInfo(output, controllerid, ldid, arrayindex)
  File "/usr/sbin/megaclisas-status", line 369, in returnArrayInfo
    NestedLDTable[int(controllerid)][int(arrayindex)] = False
IndexError: list assignment index out of range
```

Thanks for looking into it,
camypaj

**Comment by ElCoyote27** [comment]
Thanks for the report. It's clearly something I got wrong.
As a workaround, locate the line at the top of megaclisas-status that reads:
MaxNumHBA = 16
Try to changing it to:
MaxNumHBA = 32
If it works, please post the output.
Regards,
Vincent

**Comment by camypaj** [comment]
Wow, @ElCoyote27 , thanks for the quick response, and that fix - it worked like a charm! :) kudos!

Requedted output, redacted for disk model & serial:
```
root@mf-hdpbe0101:~# /usr/sbin/megaclisas-status2
-- Controller information --
-- ID | H/W Model       | RAM    | Temp | BBU    | Firmware     
c0    | PERC H730P Mini | 2048MB | 48C  | Good   | FW: 25.4.1.0004 

-- Array information --
-- ID | Type   |    Size |  Strpsz |   Flags | DskCache |   Status |  OS Path | CacheCade |InProgress   
c0u0  | RAID-1 |    279G |   64 KB |   RA,WB | Disabled |  Optimal | /dev/sda | None      |None         
c0u1  | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdb | None      |None         
c0u2  | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdc | None      |None         
c0u3  | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdd | None      |None         
c0u4  | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sde | None      |None         
c0u5  | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdf | None      |None         
c0u6  | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdg | None      |None         
c0u7  | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdh | None      |None         
c0u8  | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdi | None      |None         
c0u9  | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdj | None      |None         
c0u10 | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdk | None      |None         
c0u11 | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdl | None      |None         
c0u12 | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdm | None      |None         
c0u13 | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdn | None      |None         
c0u14 | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdo | None      |None         
c0u15 | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdp | None      |None         
c0u16 | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdq | None      |None         
c0u17 | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdr | None      |None         
c0u18 | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sds | None      |None         
c0u19 | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdt | None      |None         
c0u20 | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdu | None      |None         
c0u21 | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdv | None      |None         
c0u22 | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdw | None      |None         
c0u23 | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdx | None      |None         
c0u24 | RAID-0 |   1818G |   64 KB | ADRA,WB |  Default |  Optimal | /dev/sdy | None      |None         

-- Disk information --
-- ID   | Type | Drive Model                       | Size     | Status          | Speed    | Temp | Slot ID  | LSI Device ID
c0u0p0  | HDD  | SEAGATE   | 278.8 Gb | Online, Spun Up | 12.0Gb/s | 44C  | [32:24]  | 24      
c0u0p1  | HDD  | SEAGATE   | 278.8 Gb | Online, Spun Up | 12.0Gb/s | 42C  | [32:25]  | 25      
c0u1p0  | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 26C  | [32:0]   | 0       
c0u2p0  | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 26C  | [32:1]   | 1       
c0u3p0  | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 27C  | [32:2]   | 2       
c0u4p0  | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 26C  | [32:3]   | 3       
c0u5p0  | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 26C  | [32:4]   | 4       
c0u6p0  | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 27C  | [32:5]   | 5       
c0u7p0  | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 27C  | [32:6]   | 6       
c0u8p0  | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 29C  | [32:7]   | 7       
c0u9p0  | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 28C  | [32:8]   | 8       
c0u10p0 | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 26C  | [32:9]   | 9       
c0u11p0 | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 27C  | [32:10]  | 10      
c0u12p0 | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 26C  | [32:11]  | 11      
c0u13p0 | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 27C  | [32:12]  | 12      
c0u14p0 | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 26C  | [32:13]  | 13      
c0u15p0 | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 26C  | [32:14]  | 14      
c0u16p0 | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 28C  | [32:15]  | 15      
c0u17p0 | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 29C  | [32:16]  | 16      
c0u18p0 | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 27C  | [32:17]  | 17      
c0u19p0 | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 26C  | [32:18]  | 18      
c0u20p0 | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 25C  | [32:19]  | 19      
c0u21p0 | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 25C  | [32:20]  | 20      
c0u22p0 | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 26C  | [32:21]  | 21      
c0u23p0 | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 26C  | [32:22]  | 22      
c0u24p0 | HDD  | SEAGATE  | 1.818 TB | Online, Spun Up | 12.0Gb/s | 26C  | [32:23]  | 23      

```

**Comment by ElCoyote27** [comment]
Thanks for the feedback.. Glad it worked out.
The proper fix is in my git (please test if you have time) and I've sent a pull request to eLvErDe.

**Comment by camypaj** [comment]
Thanks again, Vincent - your fixed version works as well.

**Comment by ElCoyote27** [comment]
Thanks camypaj. :)
