### ISSUE TITLE
3ware-status error

### ISSUE THREAD

**Issue by lljoerne** [eLvErDe/hwraid#69]
#Problem 
Running 3ware-status gives following error message:

```
root@jw02:/home/jw# uname -a
Linux jw02 3.16.0-4-686-pae #1 SMP Debian 3.16.43-2+deb8u3 (2017-08-15) i686 GNU/Linux
root@jw02:/home/jw# 3ware-status
-- Controller informations --
-- ID | Model
Traceback (most recent call last):
  File "/usr/sbin/3ware-status", line 95, in <module>
    model = getOutput(cmd)[0].split(' = ')[1].strip()
IndexError: list index out of range
root@jw02:/home/jw# 3ware-status --nagios
RAID OK - Arrays: OK:4 Bad:0 - Disks: OK:7 Bad:0
root@jw02:/home/jw#
```

First time I receive the error messages. It was working fine for years on Debian jessie.

Line 95 looks like:
```
# List available controller
if not nagiosmode:
    print '-- Controller informations --'
    print '-- ID | Model'
    for controller in controllerlist:
        cmd = binarypath+' info '+controller+' model'
        model = getOutput(cmd)[0].split(' = ')[1].strip()
        print controller+' | '+model
    print ''
```

**Comment by eLvErDe** [comment]
Hey,
Can you split the getOutput call to actually print output before I try to parse it ?
Like:
output = getOutput(cmd)
model = output[0]....

Thanks

**Comment by lljoerne** [comment]
Hello!

Sorry, I am not an expert. That's what I did. Hopefully, it is what you requested.

```
# List available controller
if not nagiosmode:
    print '-- Controller informations --'
    print '-- ID | Model'
    for controller in controllerlist:
        cmd = binarypath+' info '+controller+' model'
        output = getOutput(cmd)
        print cmd
        print output
        model = output[0].split(' = ')[1].strip()
#        model = getOutput(cmd)[0].split(' = ')[1].strip()
        print model
        print controller+' | '+model
    print ''
```

```
root@jw02:/usr/sbin# 3ware-status
-- Controller informations --
-- ID | Model
/usr/sbin/tw-cli info c0 model
['/c0 Model =']
Traceback (most recent call last):
  File "/usr/sbin/3ware-status", line 98, in <module>
    model = output[0].split(' = ')[1].strip()
IndexError: list index out of range
root@jw02:/usr/sbin# tw-cli info

Ctl   Model        (V)Ports  Drives   Units   NotOpt  RRate   VRate  BBU
------------------------------------------------------------------------
c0                 8         5        3       0       2       -      -        
c3    9500S-12     12        2        1       0       5       1      -        

root@jw02:/usr/sbin# tw-cli info c0 model
/c0 Model = 

root@jw02:/usr/sbin# tw-cli info c3 model
/c3 Model = 9500S-12

root@jw02:/usr/sbin# tw-cli info c0

Unit  UnitType  Status         %RCmpl  %V/I/M  Stripe  Size(GB)  Cache  AVrfy
------------------------------------------------------------------------------
u0    RAID-1    OK             -       -       -       279.459   W      -      
u2    RAID-1    VERIFYING      -       82%     -       232.885   W      -      
u4    SPARE     OK             -       -       -       279.461   -      -      

Port   Status           Unit   Size        Blocks        Serial
---------------------------------------------------------------
p0     OK               u0     279.46 GB   586072368     5NF118CW            
p1     OK               u0     279.46 GB   586072368     3NF0H18M            
p2     OK               u2     232.88 GB   488397168     4ND2V647            
p3     OK               u2     232.88 GB   488397168     5ND4FMG1            
p4     OK               u4     279.46 GB   586072368     3NF12SS1            
p5     NOT-PRESENT      -      -           -             -
p6     NOT-PRESENT      -      -           -             -
p7     NOT-PRESENT      -      -           -             -
```

Looks like there is no model name for controller c0.
```
root@jw02:/usr/sbin# lspci | grep -i 3ware
02:05.0 RAID bus controller: 3ware Inc 7xxx/8xxx-series PATA/SATA-RAID (rev 01)
02:09.0 RAID bus controller: 3ware Inc 9xxx-series SATA-RAID
```

**Comment by TimCook1** [comment]
lspci -nn |grep 3ware 

should give you the pci device ID which you can use to determine the exact card model.

**Comment by eLvErDe** [comment]
Hi,

Sorry, I forgot this ticket. Seems you have a weird disk with no model returned. I'll provide a quick fix, can you give a try in a few minutes ? (download latest script from github an run it)

**Comment by lljoerne** [comment]
It works now:

```
root@jw02:/usr/sbin# 3ware-status
-- Controller informations --
-- ID | Model
c2 | 9500S-12
c3 | N/A

-- Arrays informations --
-- ID   Type    Size    Status
c2u0    RAID1   1862G   OK
c3u0    RAID1   279G    OK
c3u2    RAID1   232G    OK

-- Disks informations
-- ID   Model                   Status
c2u0p4  WDC WD20EZRX-32SPEB0    OK
c2u0p5  WDC WD20EZRX-32D8PB0    OK
c3u0p0  ST3300831A      OK
c3u0p1  ST3300831A      OK
c3u2p2  ST3250623A      OK
c3u2p3  ST3250624A      OK
root@jw02:/usr/sbin#
```

Thank you very much!!

**Comment by eLvErDe** [comment]
What's the hell is this c3 controller having no model name ???

**Comment by lljoerne** [comment]
```
root@jw02:/home/jw# tw-cli /c3 show all
/c3 Driver Version = 1.26.02.003
/c3 Model = 
/c3 Available Memory = 2MB
/c3 Firmware Version = FE7X 1.05.00.068
/c3 Bios Version = BE7X 1.08.00.048
/c3 Boot Loader Version = ME7X 1.01.00.040
/c3 Serial Number = 
/c3 PCB Version = Rev4
/c3 PCHIP Version = 1.30-66
/c3 ACHIP Version = 3.20
/c3 Total Optimal Units = 2
/c3 Not Optimal Units = 0 

Unit  UnitType  Status         %RCmpl  %V/I/M  Stripe  Size(GB)  Cache  AVrfy
------------------------------------------------------------------------------
u0    RAID-1    OK             -       -       -       279.459   W      -      
u2    RAID-1    OK             -       -       -       232.885   W      -      

Port   Status           Unit   Size        Blocks        Serial
---------------------------------------------------------------
p0     OK               u0     279.46 GB   586072368     5NF118CW            
p1     OK               u0     279.46 GB   586072368     3NF0H18M            
p2     OK               u2     232.88 GB   488397168     4ND2V647            
p3     OK               u2     232.88 GB   488397168     5ND4FMG1            
p4     NOT-PRESENT      -      -           -             -
p5     NOT-PRESENT      -      -           -             -
p6     NOT-PRESENT      -      -           -             -
p7     NOT-PRESENT      -      -           -             -

```
